### ISSUE TITLE
Cancel a toggle event

### ISSUE THREAD

**Issue by mattmccarley** [Twikito/easy-toggle-state#15]
I need to be able to cancel a toggle event. For instance, I am tracking mouse movement to determine if a user is clicking or dragging on a tab slider. In the event they are dragging. I would like to be able to cancel the toggle in the toggleBefore event hook.

**Comment by Twikito** [comment]
Thanks for taking time to report this issue.
Can you give me more informations about your issue, so I could be sure what you are talking about?
Any code snippets?

**Comment by mattmccarley** [comment]
I am listening to mousedown and mouseup and determining if the user is dragging. If they are dragging, I want to disable the toggle event. 

I would like to be able to do something like this:
```javascript
document.querySelector("#myTrigger").addEventListener("toggleBefore", (event) => {
   if (dragging) {
        event.cancelToggle();
    }
});
```

**Comment by mattmccarley** [comment]
Or perhaps a boolean like `event.cancelToggle = true`.

**Comment by Twikito** [comment]
Investigating…

**Comment by Twikito** [comment]
The only solution I see is that I could add a flag on the trigger, `disableToggle` for example, but since hooks are based on events and so asynchronous, this won't be solid. So I won't do that.

And by the way, I think your issue is very specific.
Maybe you should find another solution by delegating the drag and drop to a kind of "grip" element, an the toggle to the label. Otherwise, you should write another script for this specific componant.

Anyway, thanks for your support. 😃
