### ISSUE TITLE
Allow `data-toggle-arrows` without `data-toggle-group` or `data-toggle-radio-group` set

### ISSUE THREAD

**Issue by henrijs** [Twikito/easy-toggle-state#27]
I would like to use `data-toggle-arrows` in a group in which multiple targets may be active, like accordion that does not close previous target.

**Comment by Twikito** [comment]
Hi!

I thought about this since you posted it, but I think the design pattern you mentionned won't be great in many cases. Do you have a case study?

Here, navigating with arrow keys will toggle on each trigger and toggle off the others of the same group, beginning with the one which has the focus.
In your case, if I understand this well, it shouldn't toggle off the others, which means that navigating with arrow keys will toggle each trigger, regardless to its previous state. But if some triggers are already toggled on, the state won't be the same for all triggers during a pass through the group. I think this is not a good design pattern.

If you still want to navigate with arrow key without specifying a group, you can dispatch the event you specified on each trigger, and easy-toggle-state will deal with it.
