### ISSUE TITLE
Mobile Specific Control?

### ISSUE THREAD

**Issue by jezthomp** [Twikito/easy-toggle-state#46]
Is it possible to have screen size control of the toggle?

For example you have a mobile drop down menu you toggle on and off however, when you re-size the browser window it would still be there because the button you used to turn it on/off is also mobile specific?

So once you made the screen a certain size it would toggle off if it was active?

**Comment by Twikito** [comment]
Hi @jezthomp,
Thanks for taking time reporting this issue, and sorry for the delay.

Actually, you can know the state of a trigger by checking its `.isToggleActive` attribute, so when you reach the screen size, you could dispatch a `click` event on the trigger if `trigger.isToggleActive` is true.
Does this helps?

Another thought: you are resizing the browser for development / debugging purposes, but users are in a reading / searching context, so they never (or almost never) do this. So I think your issue is not really one.
