### ISSUE TITLE
Multiple Targets?

### ISSUE THREAD

**Issue by jezthomp** [Twikito/easy-toggle-state#6]
Is it possible to target multiple classes, or is that not the point, elements always have to be adjacent?

For example.

`<button class="hero-menu-button main-btn" type="button"  data-toggle-class data-toggle-escape  data-toggle-target=".navigation-panel" data-toggle-target-self=".hero-menu-button">`

Only thing that happens is `is-active` is added to the div `.navigation-panel` when i needed it adding to the actual button as well?

Many thanks.

**Comment by Twikito** [comment]
Since you target with a selector, yes, you can target multiple classes, for example `.class-a, .class-b`. Elements don't have to be adjacents.

When you use `data-toggle-class` on an element – a button for example –, you will add the `.is-active` class by clicking on it, so you don't need `data-toggle-target-self=".hero-menu-button"`.

`data-toggle-target-self` is used to target an element __inside__ the trigger element, so in your example, inside this button.
