### ISSUE TITLE
Adapt easy-toggle-state for ESM projects?

### ISSUE THREAD

**Issue by aaronstezycki** [Twikito/easy-toggle-state#63]
Just wondering if the script could be adapted to use ES module bundling? Would be great to be able to do: 

```
import { easyToggle } from '@easy-toggle-state'

... App functions {}

App.start();
```

Thanks for your help! :)

**Comment by Twikito** [comment]
Hi @aaronstezycki!

Thanks for your message.

Actually, it's the same demand as [this issue](https://github.com/Twikito/easy-toggle-state/issues/17). To be able to bound, unbound, and everything else, I need to rewrite a bunch of code, since this library wasn't thought as an api from the beginning, but a simple import or inclusion to be able to build interactions in no time.

I don't have much time these times, but I'm thinking about it 😉

**Comment by Twikito** [comment]
Hey @aaronstezycki 👋 

I'm glad to annonce you that the job is done: you can now use Easy Toggle State in ESM projects! Learn more in the [new API section in the documentation](https://twikito.github.io/easy-toggle-state/#api).
