### ISSUE TITLE
Allowing mutliple classes within toggle-class

### ISSUE THREAD

**Issue by aaronstezycki** [Twikito/easy-toggle-state#65]
Sorry if I missed this, as its not currently mentioned in the docs.

I'd like to be able to split class concerns, i.e `is-active` and `is-animating`. This allows us to use the toggle in different ways. i .e having normal behaviour on a component with `is-active`, and then applying `is-animated` to separate components that need it. 

Something like: 
```
<button class="c-btn" data-toggle-class="is-active, is-animated" data-toggle-target="[data-component]">Button</button>

<div class="component" data-component>...</div>
```

**Comment by Twikito** [comment]
Hi @aaronstezycki!
First of all, thanks for taking time to add this comment.

If I understood your comment well, you want to have a class `is-active` for active state on some triggers, and another class `is-animating` in addition for active state on others, right? That means those triggers should toggle two – or several – classes at the same time, right?

Well, I tried, and it actually doesn't work for now.
This case could be quite dangerous, since one or several of thoses classes could be already set on the trigger and/or the target on the inactive state. In this case, what should I do? Take the first class presency state only into account, and add/remove all the classes, or toggle each, regardless the presency?

This feature could be useful, be I need to choose wisely.
I think toggling each class regardless its presency could be the best practice.

For instance:
 ```html
<!-- Inactive state -->
<bouton type="button" data-toggle-class="class-1 class-2"></button>

<!-- Active state -->
<bouton type="button" data-toggle-class="class-1 class-2" class="class-1 class-2"></button>
```

Then a tricky one, but quite useful:
```html
<!-- Inactive state -->
<bouton type="button" data-toggle-class="is-active is-inactive" class="is-inactive"></button>

<!-- Active state -->
<bouton type="button" data-toggle-class="is-active is-inactive" class="is-active"></button>
```

Does these examples make any sense for you?

**Comment by Twikito** [comment]
Hi @aaronstezycki!

You can now fill `data-toggle-class` attribute with as many classes as you need. And by the way, you have now [other toggling options](https://twikito.github.io/easy-toggle-state/#toggling) too.

**Comment by aaronstezycki** [comment]
@Twikito Thanks!

I never got the chance to reply to your message, and due to lockdown I've been off work for quite some time.

In reply to the above you probably want to toggle 'states/classes' based on what the target currently has. If it currently has `is-inactive` by default on the thing your toggling, then the click would change it to `is-active` and remove `is-inactive`. 
Which I think is what you have achieved. 🎉

Thanks for getting round to adding this. 👍

Just to go one step further (more functionality, and flexibility is always a good thing)... 🤯...

You could also be explicit on what you want to 'toggle' on a target. i.e If you wanted to just add or remove a class explicitly. 
Just add a class = `++class`. Just remove a class = `--class`.

```
// Add class
<button class="c-btn" data-toggle-class="++class1" data-toggle-target="[data-component]"/>

<div class="" data-component></div>

// Remove class
<button class="c-btn" data-toggle-class="--class1" data-toggle-target="[data-component]"/>
```

This would effectively add the class, but not toggle it and allow for other buttons in the UI, to turn things on/off if they were active and not just the one button. Hope this makes sense :)

**Comment by Twikito** [comment]
Hey @aaronstezycki 👋 

Well, Easy Toggle State is about toggling, so I wont change the first idea, and in my opinion, if you only need to add or remove a class, no need to use this library.

But your request maked me think about another feature that could interest you.
Imagine a new attribute, something like `data-toggle-repetition`, in which you could fill a number, `1` for example. With this, the trigger could toggle its target•s as only the number of times as the number of repetition filled, so here once.

What do you think?
