### ISSUE TITLE
Error in IE11 and IE10

### ISSUE THREAD

**Issue by oilvier** [Twikito/easy-toggle-state#7]
Hi,

I have stumbled upon an error in Internet Explorer 11 and 10. 
I thought at first that it was coming from me, but it seems that you have the same error on the demo site.

`SCRIPT1002: Syntax error` in easy-toggle-state.es6.min.js

IE is reporting this line in error:

```js
/* Retrieve a valid HTML attribute. */
const dataset = (key => ["data", PREFIX, key].filter(Boolean).join("-"));
```

**Comment by Twikito** [comment]
Hi,

Thanks for taking time to report this issue.
Since Internet Explorer does not support ES6, you need to use the ES5 transpiled version here: https://github.com/Twikito/easy-toggle-state/blob/master/dist/easy-toggle-state.js.

Now, I made some tests with Internet Explorer 11, and there are some issues that need polyfills. I'm actually working on it.

**Comment by Twikito** [comment]
Ok, now there's a custom build for IE11 with polyfills.

**Comment by Twikito** [comment]
In addition of using ES5 version, now compatibility for Internet Explorer is provided by [polyfill.io](https://polyfill.io) which supports back to IE 7. It brings polyfills for `Array.from` and `Element.prototype.closest`.

And before you ask, yes, you can [run it locally](https://github.com/Financial-Times/polyfill-service#running-locally).
